name: CI

on:
  push:
    branches: '**'
    tags-ignore: '**'
    paths:
      - 'pak01_dir/**'
      - 'smsm/**'
  pull_request:
    branches: '**'
    paths:
      - 'pak01_dir/**'
      - 'smsm/**'
  workflow_dispatch:

jobs:
  vpk:
    name: Pack files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Pack VPK
        run: |
          wget https://github.com/craftablescience/VPKEdit/releases/download/v4.4.2/VPKEdit-Linux-Standalone-CLI-gcc-Release.zip
          unzip VPKEdit-Linux-Standalone-CLI-gcc-Release.zip
          chmod +x ./vpkeditcli
          ./vpkeditcli -s -v 1 pak01_dir

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mod-files
          path: |
            cfg/
            maps/
            resource/
            scripts/
            media/
            gameinfo.txt  
            pak01_dir.vpk
          if-no-files-found: error

  build-lin:
    name: SMSM Linux Build
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v4
          with: { fetch-depth: 0 }

        - name: Install Dependencies
          run: |
            sudo apt-get update
            sudo apt-get install -y g++-10-multilib

        - name: Build
          run: |
            cd smsm
            make -j$(nproc)

        - name: Upload Artifact
          uses: actions/upload-artifact@v4
          with:
            name: smsm-linux
            path: smsm/smsm.so
            if-no-files-found: error

  build-win:
    name: SMSM Windows Build
    runs-on: windows-2019
    steps:
        - name: Checkout
          uses: actions/checkout@v4
          with: { fetch-depth: 0 }

        - name: Setup MSBuild
          uses: microsoft/setup-msbuild@v2

        - name: Build
          run: |
            cd smsm
            msbuild -m -t:chaos -p:"Platform=x86" SMSM.sln

        - name: Upload Artifact
          uses: actions/upload-artifact@v4
          with:
            name: smsm-windows
            path: |
              smsm\bin\smsm.dll
              smsm\bin\smsm.pdb
            if-no-files-found: error

  merge:
    name: Mod Package
    needs: [vpk, build-lin, build-win]
    runs-on: ubuntu-latest
    steps:
      - name: Merge Artifacts
        uses: actions/upload-artifact/merge@v4
        with:
          name: Portal 2 Speedrun Mod
          delete-merged: true
